[project]
name = "frame-check"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "frame-check-core",
    "frame-check-lsp",
]

[tool.uv.workspace]
members = [
    "frame-check-core",
    "frame-check-lsp",
]

[tool.uv.sources]
frame-check-core = { workspace = true }
frame-check-lsp = { workspace = true }


[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "ipython>=9.14.1",
    "mypy>=2.1.0",
    "pandas>=3.0.3",
    "pandas-stubs>=3.0.3.260530",
    "pre-commit>=4.6.0",
    "pytest>=9.0.3",
    "pytest-codspeed>=5.0.3",
    "tabulate>=0.10.0",
    "tomlkit>=0.15.0",
    "types-psutil>=7.2.2.20260508",
]
docs = [
    "mkdocs-gen-files>=0.6.1",
    "mkdocs-material>=9.7.6",
    "mkdocstrings[python]>=1.0.4",
    "pymdown-extensions>=10.21.3",
    "zensical>=0.0.44",
]

[tool.pyright]
typeCheckingMode = "basic"

[tool.ruff]
exclude = ['frame-check-extensions']


[tool.frame-check]
exclude = [
    'frame-check-extensions/',
    'frame-check-core/tests'
]
